name: CI Release Draft

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
